import type {
  StrategyStatusPayload,
} from "@/lib/status/types";
import {
  STRATEGY_STATUS_SCHEMA_VERSION,
  STRATEGY_STATUS_SOURCE,
} from "@/lib/status/types";
import { provenance, section, unavailable, type Section } from "@/lib/status/vocab";
import {
  APPROVED_SHA,
  DASHBOARD_SHA,
  REPO_SHA,
  STRATEGY_IDENTITY,
  UNIVERSE_HASH,
} from "./fixtures";

const NOW = new Date("2026-08-07T17:00:00Z");

function fresh<T>(source: string, scope: string, data: T, asOf: string): Section<T> {
  return section(
    provenance({ source, scope, asOf, now: NOW, freshness: "CURRENT" }),
    data,
  );
}

/**
 * A complete, healthy payload. Tests override individual sections to express
 * one failure mode at a time.
 */
export function buildPayload(
  overrides: Partial<StrategyStatusPayload> = {},
): StrategyStatusPayload {
  return {
    schemaVersion: STRATEGY_STATUS_SCHEMA_VERSION,
    source: STRATEGY_STATUS_SOURCE,
    collectedAt: NOW.toISOString(),
    accountId: "acc-1",
    accountNickname: "Paper prod",
    accountMode: "paper",
    web: fresh(
      "dashboard runtime configuration",
      "this web deployment",
      {
        dashboardBuildSha: DASHBOARD_SHA,
        dataMode: "account-scoped" as const,
        status: "ok" as const,
        strategyVersion: "v11-adaptive-momentum",
      },
      NOW.toISOString(),
    ),
    release: fresh(
      "GitHub paper-production environment variable",
      "approved paper release and repository reference",
      {
        repositoryRefSha: REPO_SHA,
        repositoryRef: "main",
        repositoryRefCommittedAt: "2026-08-03T15:00:00Z",
        approvedPaperReleaseSha: APPROVED_SHA,
        approvedShaSource: "github-environment-variable" as const,
        releaseGate: "PASS" as const,
        releaseGateRunUrl: "https://github.com/x/y/actions/runs/1",
        releaseGateCompletedAt: "2026-08-02T16:00:00Z",
        dashboardMatchesApprovedRelease: false,
      },
      "2026-08-02T16:00:00Z",
    ),
    accountBinding: fresh(
      "dashboard server binding configuration + Supabase account record",
      "selected account Paper prod",
      {
        selectedAccountId: "acc-1",
        selectedAccountNickname: "Paper prod",
        mode: "paper" as const,
        role: "PRODUCTION_CONTROLLED_PAPER" as const,
        productionBound: true,
        bindingProof: "server-authorized-production-owner-and-account" as const,
        bindingDetail:
          "Signed-in production owner, configured production account, paper mode and account ownership all match.",
        brokerAccountMask: "••••1234",
      },
      NOW.toISOString(),
    ),
    broker: fresh(
      "Alpaca paper REST snapshot",
      "selected account Paper prod",
      {
        equity: 881_532.2,
        cash: 165_077,
        cashPct: 18.72,
        dailyPnl: 2592.2,
        dailyPnlPct: 0.29,
        grossExposure: 716_455.2,
        grossExposurePct: 81.27,
        positionCount: 10,
        positions: [],
        shortSymbols: [],
      },
      NOW.toISOString(),
    ),
    strategy: fresh(
      "github-actions artifact paper-runtime-state (server-only)",
      "approved paper release · production executor account",
      {
        strategyVersion: "v11-adaptive-momentum",
        paperOnly: true as const,
        marketGate: "RISK_ON" as const,
        marketGateSource: "frozen V11 plan risk_off flag",
        spyClose: null,
        spySma200: null,
        breadthPct: null,
        breadthNumerator: null,
        breadthDenominator: null,
        breadthMultiplierPct: null,
        recoveryLatchArmed: false,
        rollingDrawdownPct: -17.88,
        rollingPeakEquity: 1_073_504.44,
        riskLookbackSessions: 22,
        executionRiskTier: {
          tier: "CAUTIOUS" as const,
          reason: "fresh broker account and rolling-history snapshot",
          source: "production run record (authoritative for that cycle)",
          asOf: "2026-08-07T16:05:05Z",
        },
        persistedRiskTier: {
          tier: "CAUTIOUS" as const,
          reason: null,
          source: "saved runtime performance.json",
          asOf: "2026-08-07T12:05:05Z",
        },
        riskTierConflict: false,
        plan: null,
        runtimeEquity: 881_532.2,
        runtimeCash: 165_077,
        runtimePositionCount: 10,
        runtimeSnapshotAt: "2026-08-07T12:05:05Z",
      },
      "2026-08-07T16:05:05Z",
    ),
    universe: fresh(
      "production preflight report + frozen V11 plan",
      "ranking universe used by the production executor",
      {
        source: "validated-watchlist-fallback",
        symbolCount: 540,
        rankingUniverseSha256: UNIVERSE_HASH,
        eligibleCount: 78,
        selectedCount: 10,
        cacheState: "validated-watchlist-fallback" as const,
      },
      "2026-08-07T16:04:52Z",
    ),
    validation: fresh(
      "repository state/backtest/v11_validation.json",
      "canonical fixed-strategy promotion evidence",
      {
        status: "PASS" as const,
        allowedMode: "paper-validation-eligible",
        generatedAt: "2026-08-02T15:56:49Z",
        barBoundaryDate: "2026-07-10",
        expiresAt: "2026-08-14T00:00:00Z",
        expiryBasis: "bar-boundary" as const,
        checksPassed: 8,
        checksEvaluated: 8,
        strategyIdentityValue: STRATEGY_IDENTITY,
        rankingUniverseSha256: UNIVERSE_HASH,
        barSnapshotSha256: "b".repeat(64),
        contractSchemaVersion: 1,
        contractAlgorithm: "sha256",
        rankingUniverseCount: 540,
        startingCapital: 1_000_000,
        slippageScenariosBps: [7, 15],
        identityMatchesRuntime: "PASS" as const,
        universeMatchesRuntime: "PASS" as const,
        reportSha256: "digest",
        metrics: [],
        warnings: [],
        readAtRef: APPROVED_SHA,
      },
      "2026-08-02T15:56:49Z",
    ),
    preflight: fresh(
      "github-actions artifact paper-diagnostics (server-only)",
      "last successful production preflight",
      {
        status: "PASS" as const,
        checkedAt: "2026-08-07T16:04:52Z",
        checksPassed: 18,
        checksEvaluated: 18,
        allowedMode: "paper",
        marketOpen: true,
        accountStatus: "ACTIVE",
        positionCount: 10,
        openOrderCount: 0,
        openBuyCount: 0,
        shortCount: 0,
        strategyIdentity: "identity",
        universeCount: 540,
        universeSource: "validated-watchlist-fallback",
        universeSha256: UNIVERSE_HASH,
        barSnapshotThroughDate: "2026-07-10",
        validationStatus: "PASS",
        riskTier: "CAUTIOUS" as const,
        riskSnapshotReason: "fresh broker account and rolling-history snapshot",
        runtimeVersions: { python: "3.12.11" },
        checks: [],
        runUrl: "https://github.com/x/y/actions/runs/2",
      },
      "2026-08-07T16:04:52Z",
    ),
    execution: fresh(
      "github-actions artifact paper-runtime-state (server-only)",
      "last successful executor cycle",
      {
        status: "PASS" as const,
        completedAt: "2026-08-07T16:05:05Z",
        releaseSha: APPROVED_SHA,
        strategyVersion: "v11-adaptive-momentum",
        paperOnly: true,
        marketEntryAllowed: true,
        riskTier: "CAUTIOUS" as const,
        actionCounts: { ADAPTIVE_PLAN: 1 },
        blockingReason: null,
        runUrl: "https://github.com/x/y/actions/runs/2",
      },
      "2026-08-07T16:05:05Z",
    ),
    operations: fresh(
      "GitHub Actions workflow runs",
      "paper-production.yml",
      {
        latestAttempt: {
          runId: 2,
          runNumber: 42,
          attempt: 1,
          status: "completed",
          conclusion: "success",
          startedAt: "2026-08-07T16:00:00Z",
          completedAt: "2026-08-07T16:05:30Z",
          triggerSha: REPO_SHA,
          event: "schedule",
          url: "https://github.com/x/y/actions/runs/2",
          infrastructureFailure: false,
          failureKind: null,
        },
        lastSuccessfulRun: null,
        workflowUrl: "https://github.com/x/y/actions/workflows/paper-production.yml",
      },
      "2026-08-07T16:05:30Z",
    ),
    tournament: fresh(
      "repository state/backtest/strategy_tournament_epoch_1.json",
      "frozen epoch-1 research evidence",
      {
        epoch: 1,
        status: "COMPLETE",
        decision: "RETAIN_V11",
        productionChanged: false,
        researchOnly: true,
        generatedAt: "2026-08-03T15:00:00Z",
        eligibleChallengerCount: 0,
        shadowChallenger: null,
        primaryCostBps: 15,
        candidates: [],
        warnings: [],
        protocolPath: "strategy/strategy_tournament_epoch_1.md",
        readAtRef: "main",
      },
      "2026-08-03T15:00:00Z",
    ),
    authorization: fresh(
      "dashboard server authorization configuration",
      "viewer 00000000… · account Paper prod",
      {
        productionRuntimeAuthorized: true,
        denialReason: null,
        detail:
          "Signed-in production owner, configured production account, paper mode and account ownership all match.",
      },
      NOW.toISOString(),
    ),
    convergence: unavailable(
      "frozen V11 plan + broker snapshot",
      "frozen plan vs Paper prod",
      "no frozen V11 plan is available from the private runtime artifact",
    ),
    validationGate: {
      effective: "PASS" as const,
      reportAssessment: "PASS" as const,
      reasons: [],
      details: [],
      expiresAt: "2026-08-14T00:00:00Z",
    },
    warnings: [],
    ...overrides,
  };
}

export { NOW as PAYLOAD_NOW };
